package generator_test

import (
	"bytes"
	"context"
	"errors"
	"testing"

	"github.com/xuri/excelize/v2"

	report "axis-flow-back/internal/report"
	"axis-flow-back/internal/report/generator"
)

func validXLSXRequest() report.ReportRequest {
	empID := "emp-99"
	return report.ReportRequest{
		Type:         "payroll",
		OutputFormat: report.FormatXLSX,
		UserID:       "user-2",
		EmpresaID:    "empresa-2",
		Filters: report.ReportFilters{
			DateFrom:   "2024-06-01",
			DateTo:     "2024-06-30",
			EmployeeID: &empID,
		},
	}
}

func TestXLSXGenerator_Generate_ReturnsXLSX(t *testing.T) {
	gen := generator.NewXLSXGenerator()
	ctx := context.Background()

	data, err := gen.Generate(ctx, validXLSXRequest())
	if err != nil {
		t.Fatalf("expected no error, got: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("expected non-empty bytes")
	}

	f, err := excelize.OpenReader(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("excelize could not open generated bytes: %v", err)
	}

	sheets := f.GetSheetList()
	if len(sheets) == 0 {
		t.Fatal("expected at least one sheet")
	}
	found := false
	for _, s := range sheets {
		if s == "Sheet1" {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("Sheet1 not found; sheets: %v", sheets)
	}

	rows, err := f.GetRows("Sheet1")
	if err != nil {
		t.Fatalf("could not get rows: %v", err)
	}
	if len(rows) <= 1 {
		t.Fatalf("expected more than 1 row (header + data), got %d", len(rows))
	}
}

func TestXLSXGenerator_WrongFormat(t *testing.T) {
	gen := generator.NewXLSXGenerator()
	ctx := context.Background()

	req := validXLSXRequest()
	req.OutputFormat = report.FormatPDF

	_, err := gen.Generate(ctx, req)
	if !errors.Is(err, report.ErrInvalidFormat) {
		t.Fatalf("expected ErrInvalidFormat, got: %v", err)
	}
}
